# gensymbols.ps1
# A.R.C. v4 — Symbol Index Generator
# Scans all .cs files in MosquitoNetCalculator/ and generates
# docs/arc/SYMBOL_INDEX.md with class→member→file mapping.
# Usage: powershell -ExecutionPolicy Bypass -File gensymbols.ps1

$ErrorActionPreference = "Stop"
$projectRoot = $PSScriptRoot
$srcDir = Join-Path $projectRoot "MosquitoNetCalculator"
$outputPath = Join-Path $projectRoot "docs\arc\SYMBOL_INDEX.md"

# Patterns for extraction
$classPattern = '^\s*(public|internal|static)\s+(partial\s+)?(class|struct|enum|static class)\s+(\w+)'
$propertyPattern = '^\s*(public|internal|static)\s+(\w[\w<>?\[\],\s]*)\s+(\w+)\s*\{'  # property with get/set
$methodPattern = '^\s*(public|internal|static)\s+(\w[\w<>?\[\],\s]*)\s+(\w+)\s*\('   # method
$namespacePattern = '^\s*namespace\s+(\S+)'

$files = Get-ChildItem -Path $srcDir -Filter "*.cs" -Recurse | 
    Where-Object { $_.FullName -notmatch '\\obj\\' -and $_.FullName -notmatch '\\bin\\' } |
    Sort-Object Name

$modules = @{}  # module name → classes

function Get-RelativePath($fullPath) {
    return $fullPath.Replace("$projectRoot\", "").Replace("\", "/")
}

foreach ($file in $files) {
    $content = Get-Content $file.FullName -Raw -Encoding UTF8
    if (-not $content) { continue }
    
    $relativePath = Get-RelativePath $file.FullName
    $lines = $content -split '\r?\n'
    
    $namespace = ""
    $currentClass = $null
    
    for ($i = 0; $i -lt $lines.Count; $i++) {
        $line = $lines[$i].Trim()
        
        # Skip comments and attributes
        if ($line -match '^\s*//' -or $line -match '^\s*/\*' -or $line -match '^\s*\*') { continue }
        if ($line -match '^\s*\[.*\]\s*$') { continue }  # attributes
        if ($line -match '^#') { continue }
        
        # Namespace
        if ($line -match $namespacePattern) {
            $namespace = $Matches[1]
            continue
        }
        
        # Class/struct/enum declaration
        if ($line -match $classPattern) {
            $className = $Matches[4]
            
            # Skip generated/designer files
            if ($className -match 'Designer|AssemblyInfo|Generated') { 
                $currentClass = $null
                continue 
            }
            
            $currentClass = @{
                Name = $className
                Namespace = $namespace
                File = $relativePath
                Type = $Matches[3]
                Properties = @()
                Methods = @()
                Fields = @()
                StaticMembers = @()
            }
            continue
        }
        
        # Skip lines inside method bodies — approximate: skip lines after { that are indented with at least 8 spaces
        # We use a simple heuristic: we're inside a method body if we've seen a line with { and no closing }
        # This is intentionally simple — regex-based parsing is approximate
        
        if (-not $currentClass) { continue }
        
        # Property
        if ($line -match $propertyPattern) {
            $propName = $Matches[3]
            # Filter out method bodies (heuristic)
            if ($propName -notmatch '^if$|^for$|^while$|^foreach$|^switch$|^catch$|^using$|^lock$|^return$') {
                $entry = "$propName"
                $currentClass.Properties += $entry
                if ($line -match '\bstatic\b') {
                    $currentClass.StaticMembers += "P:$propName"
                }
            }
            continue
        }
        
        # Method
        if ($line -match $methodPattern) {
            $methodName = $Matches[3]
            # Filter out control flow keywords and constructors that match like fields
            if ($methodName -notmatch '^if$|^for$|^while$|^foreach$|^switch$|^catch$|^new$|^return$|^throw$|^typeof$|^sizeof$|^nameof$|^lock$|^using$|^get$|^set$|^add$|^remove$|^class$|^struct$|^enum$|^interface$') {
                $entry = "$methodName"
                $currentClass.Methods += $entry
                if ($line -match '\bstatic\b') {
                    $currentClass.StaticMembers += "M:$methodName"
                }
            }
            continue
        }
    }
    
    if ($currentClass) {
        $moduleKey = $relativePath -replace '^MosquitoNetCalculator/(.*)/[^/]+\.cs$', '$1'
        if (-not $modules.ContainsKey($moduleKey)) {
            $modules[$moduleKey] = @()
        }
        # De-duplicate
        $modules[$moduleKey] = @($modules[$moduleKey] | Where-Object { $_.Name -ne $currentClass.Name }) + @($currentClass)
    }
}

# Generate SYMBOL_INDEX.md
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# SYMBOL_INDEX.md")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("> Auto-generated by gensymbols.ps1. Regenerate after adding/removing classes.")
[void]$sb.AppendLine(">")
[void]$sb.AppendLine("> **How AI agents use this:** On the Context phase, grep this file for the symbol you need.")
[void]$sb.AppendLine("> Instead of reading full source files, find the class here, then use code_searcher")
[void]$sb.AppendLine("> to locate the specific method/property line in the source file.")
[void]$sb.AppendLine(">")
[void]$sb.AppendLine("> **Token savings:** ~90% for symbol lookup tasks (read 300-line index vs 2000+ lines of source).")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Class Index by Module")
[void]$sb.AppendLine("")

$sortedModules = $modules.Keys | Sort-Object
foreach ($module in $sortedModules) {
    $classes = $modules[$module] | Sort-Object { $_.Name }
    if ($classes.Count -eq 0) { continue }
    
    [void]$sb.AppendLine("### $module")
    [void]$sb.AppendLine("")
    
    foreach ($cls in $classes) {
        # Build a compact entry
        $props = ($cls.Properties | Sort-Object -Unique) -join ', '
        $methods = ($cls.Methods | Sort-Object -Unique) -join ', '
        $fields = ($cls.Fields | Sort-Object -Unique) -join ', '
        $statics = ($cls.StaticMembers | Sort-Object -Unique) -join ', '
        
        $fileShort = $cls.File -replace '^MosquitoNetCalculator/', ''
        
        [void]$sb.Append("| ")
        [void]$sb.Append($cls.Name)
        [void]$sb.Append(" | ")
        [void]$sb.Append($cls.Type)  
        [void]$sb.Append(" | ")
        [void]$sb.Append($fileShort)
        [void]$sb.Append(" |")
        
        if ($props) {
            [void]$sb.Append(" Props: ")
            [void]$sb.Append($props)
        }
        if ($methods) {
            [void]$sb.Append(" | Methods: ")
            [void]$sb.Append($methods)
        }
        if ($statics) {
            [void]$sb.Append(" | Static: ")
            [void]$sb.Append($statics)
        }
        [void]$sb.AppendLine(" |")
    }
    [void]$sb.AppendLine("")
}

# Add quick-search section for common symbols
[void]$sb.AppendLine("---")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Quick-search: common symbol → file")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| Symbol | File(s) |")
[void]$sb.AppendLine("|---|---|")

$quickLookup = @{}
foreach ($module in $sortedModules) {
    foreach ($cls in $modules[$module]) {
        $fileShort = $cls.File -replace '^MosquitoNetCalculator/', ''
        foreach ($p in ($cls.Properties | Sort-Object -Unique)) {
            $key = ".$p (prop)"
            if (-not $quickLookup.ContainsKey($key)) { $quickLookup[$key] = @() }
            $quickLookup[$key] += $fileShort
        }
        foreach ($m in ($cls.Methods | Sort-Object -Unique)) {
            $key = "$m() (method)"
            if (-not $quickLookup.ContainsKey($key)) { $quickLookup[$key] = @() }
            $quickLookup[$key] += $fileShort
        }
    }
}

# Show most important symbols first (filter to commonly searched)
$importantSymbols = @(
    'Recalculate', 'Width', 'Height', 'Quantity', 'Price', 'Name', 'Color',
    'Total', 'CalculatedValue', 'CalculatedValueDisplay', 'QuantityDisplay',
    'TotalDisplay', 'PriceDisplay', 'IsAnwis', 'IsManualPiece', 'IsAmountOnly',
    'IsWidthOnly', 'IsInstallationApplicable', 'ManualPieceProducts',
    'AmountOnlyProducts', 'AreaBasedProducts', 'NoColorProducts', 'WidthOnlyProducts',
    'Clone', 'SetAnwisModeQuiet', 'AnwisSizeMode',
    'InstallationMode', 'InstallationDeduction', 'TotalWithDeduction',
    'LoadPrices', 'SavePrices', 'GetPrice', 'DefaultPrices',
    'GenerateKpHtml', 'EscapeHtml',
    'Generate', 'BuildSelectableItems',
    'LoadFromOrderData', 'AddItem', 'DeleteItem', 'ClearAll', 'CalculateTotal',
    'CurrentVersion', 'CheckOnStartupAsync', 'CheckAndApplyAsync',
    'AllNewestFirst'
)

foreach ($sym in $importantSymbols) {
    $propKey = ".$sym (prop)"
    $methKey = "$sym() (method)"
    
    if ($quickLookup.ContainsKey($propKey)) {
        $files = ($quickLookup[$propKey] | Sort-Object -Unique) -join ', '
        [void]$sb.AppendLine("| `$sym` | $files |")
    }
    elseif ($quickLookup.ContainsKey($methKey)) {
        $files = ($quickLookup[$methKey] | Sort-Object -Unique) -join ', '
        [void]$sb.AppendLine("| `$methKey` | $files |")
    }
    else {
        # Try case-insensitive lookup
        $found = $false
        foreach ($k in $quickLookup.Keys) {
            if ($k -match [regex]::Escape($sym)) {
                $files = ($quickLookup[$k] | Sort-Object -Unique) -join ', '
                [void]$sb.AppendLine("| `$k` | $files |")
                $found = $true
                break
            }
        }
        if (-not $found) {
            # Search all classes for static sets
            foreach ($module in $sortedModules) {
                foreach ($cls in $modules[$module]) {
                    $allMembers = @($cls.Properties) + @($cls.Methods) + @($cls.StaticMembers)
                    if ($allMembers -contains $sym) {
                        $fileShort = $cls.File -replace '^MosquitoNetCalculator/', ''
                        [void]$sb.AppendLine("| `$sym` | $fileShort |")
                        $found = $true
                        break
                    }
                }
                if ($found) { break }
            }
        }
    }
}

[void]$sb.AppendLine("")
[void]$sb.AppendLine("---")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Usage in A.R.C. workflow")
[void]$sb.AppendLine("")
[void]$sb.AppendLine('```')
[void]$sb.AppendLine('Context phase: grep SYMBOL_INDEX.md for the class/method you need')
[void]$sb.AppendLine('  -> find file path')
[void]$sb.AppendLine('  -> use code_searcher for the exact line')
[void]$sb.AppendLine('  -> read only relevant file sections')
[void]$sb.AppendLine('```')
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Source files")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("- gensymbols.ps1 — generates this file")
[void]$sb.AppendLine("- MosquitoNetCalculator/**/*.cs — source files scanned")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Last generated")
[void]$sb.AppendLine("")
[void]$sb.AppendLine((Get-Date -Format "yyyy-MM-dd (gensymbols.ps1)"))

# Write output
[System.IO.File]::WriteAllText($outputPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($true))
Write-Host "SYMBOL_INDEX.md generated: $outputPath"
Write-Host "  Modules: $($modules.Count)"
Write-Host "  Classes: $(($modules.Values | ForEach-Object { $_.Count } | Measure-Object -Sum).Sum)"
