#!/usr/bin/env python3
"""Russian translations for Freebuff Desktop UI strings.

Keyed by index into the candidate list (see candidates_indexed.txt).
Indices with no entry are intentionally left in English
(model names, SVG paths, commands, etc.).
"""
RU_BY_INDEX = {
    0: "Отмена",
    1: "Попробовать снова",
    2: "неизвестная ошибка",
    3: "Оформление",
    4: "Закрыть",
    5: "Копировать команду",
    6: "Удалить",
    7: "Не сейчас",
    8: "Удалить комментарий",
    9: "Повторить",
    10: "Добавить новые навыки",
    11: "Все",
    12: "Отменить вход",
    13: "Копировать заметку",
    14: "Удалить заметку",
    15: "Отбросить это отложенное сообщение",
    16: "Готово",
    17: "Скачать вручную",
    18: "Изменить",
    19: "Изменить заметку",
    20: "Изменить промпт",
    21: "Фильтровать файлы",
    22: "GLM 5.2 разблокирован",
    23: "Оставить отзыв",
    24: "Загрузка файла…",
    25: "Миссия решает, что делать дальше",
    26: "Новые сообщения",
    27: "Премиум-модель",
    28: "Очередь",
    29: "Убрать",
    30: "Удалить вложение",
    31: "Откатить сообщение",
    32: "Стартовый скрипт",
    33: "1 день",
    34: "только одна вкладка",
    35: "1 неделя",
    36: "2 недели",
    37: "3 дня",
    38: "30 дней",
    39: "Сбой, ошибка или проблема интерфейса",
    40: "Активные",
    41: "Реклама",
    42: "Добавить в чат",
    43: "Запрошен доступ администратора",
    44: "Агент работает",
    45: "Список задач агента",
    46: "Агенты выполняют shell-команды в bash, которого нет в Windows. Git for Windows включает bash и устанавливается примерно за минуту.",
    47: "Все проекты",
    48: "Агент открывает отдельную HTML-страницу или запускает dev-сервер проекта из рабочей области треда и показывает его здесь.",
    49: "Идея, вопрос или что-то ещё",
    50: "Баг приложения",
    51: "Применить все закоммиченные и незакоммиченные изменения из этого треда в папку проекта как незакоммиченные правки",
    52: "Архивировать неактивные треды через",
    53: "Архив",
    54: "Прикрепить файлы, фото или папку",
    55: "Назад к навыкам",
    56: "Плохой результат",
    57: "Бинарный файл.",
    58: "Ветка",
    59: "Кэшированный ввод (включён)",
    60: "Отмена (Esc)",
    61: "Отменить загрузку",
    62: "Изменения",
    63: "Область изменений",
    64: "Проверка обновлений",
    65: "Получать награды и отслеживать приглашения",
    66: "Очистить всё",
    67: "Нажмите на строку, чтобы оставить комментарий",
    68: "Закрыть отзыв",
    69: "Закрыть предпросмотр изображения",
    70: "Сначала закройте его открытые вкладки",
    71: "Закрыть настройки проекта",
    72: "Закрыть поиск (Esc)",
    73: "Закрыть поиск навыков",
    74: "Закрыть окно обновления",
    75: "Закрыть окно",
    76: "Безопасно закрываемся и перезапускаем обновлённое приложение.",
    77: "Облако",
    78: "Codex обновлён — отправь сообщение ещё раз.",
    79: "Кодинг-агент и модель",
    80: "Команда",
    81: "Комментарий к этой строке — отправится с вашим следующим сообщением",
    82: "Сжатие истории",
    83: "Сжимать при",
    84: "Подключите GitHub, чтобы получить право ↗",
    85: "Подключение…",
    86: "Контекст",
    87: "Копировать код",
    88: "Не удалось изменить усилие миссии",
    89: "Не удалось проверить обновления",
    90: "Не удалось получить список файлов",
    91: "Не удалось перенести сессию в эту вкладку.",
    92: "Не удалось поставить эту подсказку в очередь",
    93: "Не удалось прочитать этот файл",
    94: "Не удалось установить обновление.",
    95: "Не удалось сохранить миссию",
    96: "Не удалось задать стартовую ветку",
    97: "Не удалось начать вход.",
    98: "Не удалось отправить этот элемент",
    99: "Не удалось получить список файлов",
    100: "Не удалось загрузить изменения",
    101: "Не удалось загрузить этот тред",
    102: "Не удалось открыть этот файл",
    103: "Не удалось открыть вашу рабочую область",
    104: "Создать с нуля",
    105: "Суммарное использование по данным провайдера в текущем транскрипте треда.",
    106: "Тёмная",
    107: "Данные и вход",
    108: "Удалить навык",
    109: "Запретить",
    110: "Дизайн",
    111: "Отменить все ожидающие комментарии",
    112: "Обзор",
    113: "Документы",
    114: "Скачать Git для Windows",
    115: "Скачать установщик",
    116: "Черновик",
    117: "Перетащите строку, чтобы изменить порядок",
    118: "Перетащите, чтобы изменить порядок",
    119: "Перетащите файлы, фото или папки для прикрепления",
    120: "Каждое подтверждённое приглашение даёт ежедневную 1-часовую сессию самой мощной open-source модели",
    121: "Изменить перед отправкой",
    122: "Завершилось ошибкой",
    123: "Завершает сессию другой вкладки.",
    124: "Введите bash-команду или оставьте поле пустым.",
    126: "Файлы",
    127: "Файлы, изменённые в этом ходе",
    128: "Фильтровать популярные навыки по категории",
    129: "Завершено",
    130: "Смотрите подробности в транскрипте треда.",
    131: "Форкнуть отсюда",
    132: "GLM 5.2 — дашборд ↗",
    133: "GLM 5.2 — сегодня использовано сессий",
    137: "Git и деплой",
    138: "Хороший результат",
    139: "Изображения",
    140: "Включать инструкции AGENTS.md (или CLAUDE.md) вашего проекта в контекст агента. Применяется ко всем тредам с их следующего сообщения.",
    141: "Включает версию приложения и операционную систему.",
    142: "Ввод",
    143: "Установить и перезапустить",
    144: "Установить в простое",
    145: "Изолированный",
    146: "Приложение перезапустится после завершения вашей текущей работы.",
    147: "Оставить эту версию",
    148: "Продолжать работу",
    149: "Языки",
    150: "Последняя",
    151: "Светлая",
    152: "Загрузка изменений",
    153: "Загрузка просмотрщика изменений…",
    154: "Загрузка изменений…",
    155: "Загрузка файлов",
    156: "Загрузка настроек проекта…",
    157: "Загрузка треда…",
    159: "Как в системе",
    160: "Свернуть",
    161: "Свернуть окно",
    162: "Переместить Freebuff в «Программы»",
    163: "Перенести в новое окно",
    164: "Название",
    165: "Требует внимания",
    166: "Никогда",
    167: "Новый тред",
    168: "Без изменений",
    169: "Нет изменений для показа.",
    170: "Нет интернета — ходы возобновятся после переподключения",
    171: "Рабочей копии ещё нет",
    172: "Заметки",
    173: "Открыть",
    174: "Открыть PR",
    175: "Открыть терминал",
    176: "Открыть проект",
    177: "Открытые треды",
    178: "Открыть →",
    179: "Открытие вашей рабочей области…",
    182: "Другое",
    183: "Вывод",
    184: "Поставить очередь на паузу",
    185: "Ожидающие комментарии к коду",
    186: "Выберите проект и начните тред или продолжите с того места, где остановились.",
    187: "Закреплённые",
    188: "Популярные навыки",
    189: "Премиум",
    190: "Подготовка предпросмотра",
    191: "Предпросмотр",
    192: "Проект",
    193: "Файлы проекта",
    194: "Настройки проекта",
    195: "Проекты",
    196: "История промптов",
    197: "Защищено от автоматического архивирования",
    198: "Качество",
    199: "Чтение рабочей области треда…",
    200: "Рассуждения",
    201: "Вывод рассуждений (включён)",
    202: "Недавние",
    203: "Рекомендуемые",
    204: "Переподключение…",
    205: "Приглашайте друзей, чтобы получить больше бесплатных сессий",
    206: "Пригласите друзей, чтобы разблокировать GLM 5.2",
    207: "Приглашения засчитываются после подключения аккаунта GitHub (старше 4 месяцев)",
    208: "Перезагрузить",
    209: "Перезагрузить страницу",
    210: "Убрать контекст терминала",
    211: "Переименовать тред",
    212: "Сообщить о проблеме или идее",
    213: "Изменить размер панели обзора",
    214: "Разобрать с агентом",
    215: "Перезапустить",
    216: "Перезапустить сейчас",
    217: "Восстановить встроенный",
    218: "Продолжить очередь",
    219: "Продолжить очередь",
    220: "Выполнять эту bash-команду один раз в каждой новой изолированной рабочей области — после первого сообщения и до запуска агента. В локальных тредах она не выполняется.",
    221: "Сохранить",
    222: "Сохранить комментарий",
    223: "Сохранить изменённую копию для",
    224: "Сохранить заметку",
    225: "Сохранить заметку (Enter)",
    226: "Прокрутить к последнему",
    227: "Поиск навыков",
    228: "Поиск навыков для добавления…",
    229: "Безопасность",
    230: "Выберите тред, чтобы увидеть инструменты.",
    231: "Показываются первые 512 КБ",
    232: "Войдите, чтобы открыть проект и начать первый тред.",
    233: "Войдите, чтобы отправить отзыв",
    234: "Название навыка",
    235: "Навыки",
    236: "Пропустить эту версию",
    237: "Часть данных об использовании треда отсутствует",
    238: "Что-то пошло не так",
    239: "Что-то сработало особенно хорошо",
    241: "Создать новый проектный навык по шаблону с подсказками",
    242: "Начните работу с Freebuff",
    243: "Начато с",
    244: "Начинается с",
    245: "Отложенные сообщения",
    246: "Остановлено",
    247: "Предлагаемые следующие шаги",
    248: "Расскажите подробнее",
    249: "Терминал",
    250: "Контекст терминала для следующего промпта",
    251: "Контекст терминала — отправится с вашим сообщением",
    252: "Агент что-то упустил или сломал",
    253: "Эти суммы включают только запросы, зафиксированные до прерывания.",
    254: "Мышление",
    255: "Эта команда получит полный доступ администратора. Freebuff откроет системный запрос аутентификации вашей операционной системы только после вашего подтверждения здесь.",
    256: "Это безвозвратно удалит все архивированные треды проекта и их сохранённое состояние рабочей копии.",
    257: "Этот проект",
    258: "Слот у этой вкладки — отправьте сообщение ещё раз.",
    259: "Каталог тредов",
    260: "Использование токенов треда",
    261: "Инструменты треда",
    262: "Использование треда",
    263: "Задачи",
    264: "Незакоммичено",
    265: "Проверка обновлений здесь недоступна",
    266: "Обновления проверяются перед установкой.",
    267: "Использовать изолированную рабочую область",
    268: "Добро пожаловать в Freebuff",
    269: "Какой это тип отзыва?",
    270: "Рабочий процесс",
    271: "Изменения рабочей директории",
    272: "Вы можете продолжать работу, пока загружается обновление.",
    273: "Ваш черновик останется здесь, пока вы завершите вход.",
    274: "Ваша подписка",
    276: "ветка по умолчанию",
    277: "предпросмотр треда",
    278: "работаем…",
    279: "⇥ открыть",
}

# Bare quoted literals (ternaries, status-label maps, arrays) — display-only,
# applied with safety checks against code comparisons in apply.py.
RU_BARE = {
    " Delete all": " Удалить все",
    " Mark handled": " Отметить обработанным",
    " Move down": " Переместить вниз",
    " Move up": " Переместить вверх",
    " Remove from projects": " Убрать из проектов",
    " Switch to DeepSeek V4 Flash to keep going.": "Переключитесь на DeepSeek V4 Flash, чтобы продолжить.",
    "Add to queue": "Добавить в очередь",
    "Add to queue (Enter)": "Добавить в очередь (Enter)",
    "Administrator request": "Запрос прав администратора",
    "After everything above finishes, close this tab and clean up the thread": "После завершения всего перечисленного закройте эту вкладку и приберите тред",
    "Agent Skill · edits SKILL.md": "Навык агента · редактирует SKILL.md",
    "Agent changed ": "Агент изменил ",
    "All up to date": "Всё актуально",
    "Approve command": "Разрешить команду",
    "Archive thread": "Архивировать тред",
    "Archived thread": "Тред в архиве",
    "Attaching files needs the desktop app": "Для прикрепления файлов нужно десктопное приложение",
    "Balanced agentic coding model for everyday work": "Сбалансированная агентная модель для повседневной работы",
    "Bare minimum deliberation": "Минимальное обдумывание",
    "Branch this thread starts from before its changes are applied to your project folder": "Ветка, с которой начинается тред, до применения его изменений в вашу папку проекта",
    "Capture ideas as they come": "Записывайте идеи по мере появления",
    "Choosing a folder needs the desktop app.": "Для выбора папки нужно десктопное приложение.",
    "Close tab when done": "Закрыть вкладку по завершении",
    "Collapse explorer": "Свернуть обзор",
    "Complete a bounty to unlock": "Выполните задание, чтобы разблокировать",
    "Connection problem": "Проблема с подключением",
    "Could not change the mission": "Не удалось изменить миссию",
    "Could not delete that item": "Не удалось удалить этот элемент",
    "Could not edit that item": "Не удалось изменить этот элемент",
    "Could not open Freebuff’s data folder.": "Не удалось открыть папку данных Freebuff.",
    "Could not pause the queue": "Не удалось поставить очередь на паузу",
    "Could not reorder the queue": "Не удалось изменить порядок очереди",
    "Could not save your notes": "Не удалось сохранить ваши заметки",
    "Could not start sign-in — Freebuff’s local service is not responding. Restart the app.": "Не удалось начать вход — локальный сервис Freebuff не отвечает. Перезапустите приложение.",
    "Current branch": "Текущая ветка",
    "Current branch in this shared folder — pick another to switch": "Текущая ветка в этой общей папке — выберите другую, чтобы переключиться",
    "Daily limit": "Дневной лимит",
    "Deepest available, slowest": "Самое глубокое обдумывание, самый медленный",
    "Delete all": "Удалить все",
    "Delete the queued close action to cancel": "Удалите запланированное закрытие, чтобы отменить",
    "Describe the issue or feature you’d like to see.": "Опишите проблему или функцию, которую хотели бы видеть.",
    "Development build": "Сборка для разработки",
    "Downloading Freebuff ": "Загрузка Freebuff ",
    "Draggable item ": "Перетаскиваемый элемент ",
    "Dragging was cancelled. Draggable item ": "Перетаскивание отменено. Перетаскиваемый элемент ",
    "Edit skill": "Изменить навык",
    "Edit your message — Enter resends from here": "Измените сообщение — Enter отправит его заново отсюда",
    "Every copy is removed from disk, including any personal one shared across projects.": "Все копии удаляются с диска, включая личную копию, доступную во всех проектах.",
    "Everything it has": "Всё, что доступно",
    "Expand explorer": "Развернуть обзор",
    "Extra high": "Очень высокое",
    "Fast and affordable agentic coding model": "Быстрая и доступная агентная модель для кода",
    "Fastest replies, least deliberation": "Самые быстрые ответы, минимум обдумывания",
    "Feedback sent. Thank you!": "Отзыв отправлен. Спасибо!",
    "Files only": "Только файлы",
    "Find files": "Найти файлы",
    "Finish setup": "Завершить настройку",
    "Freebuff built-in · saving creates a standard Agent Skill copy": "Встроенный Freebuff · при сохранении создаётся стандартная копия навыка агента",
    "Freebuff could not reach the update service. Try again, or download the latest installer.": "Freebuff не смог связаться со службой обновлений. Попробуйте ещё раз или скачайте последний установщик.",
    "Freebuff needs Git Bash": "Freebuff требует Git Bash",
    "Freebuff skill": "Навык Freebuff",
    "Freebuff update": "Обновление Freebuff",
    "Help us make Freebuff better.": "Помогите нам сделать Freebuff лучше.",
    "Include AGENTS.md": "Включать AGENTS.md",
    "Inserting skill…": "Вставка навыка…",
    "Install a packaged Freebuff build to test automatic updates.": "Установите собранную версию Freebuff, чтобы проверить автоматические обновления.",
    "Install now for the quickest update, or let Freebuff wait until your active work is finished.": "Установите сейчас — это самый быстрый способ обновления, или позвольте Freebuff подождать до завершения вашей работы.",
    "Installing Freebuff ": "Установка Freebuff ",
    "Jot an idea for this project…": "Запишите идею для этого проекта…",
    "Jot an idea…": "Запишите идею…",
    "Keep using ": "Продолжить использовать ",
    "Latest frontier agentic coding model": "Последняя передовая агентная модель",
    "Learn more": "Подробнее",
    "Let the current turn finish, then pause queued work": "Дать текущему ходу завершиться, затем поставить очередь на паузу",
    "Loading notes…": "Загрузка заметок…",
    "Log file": "Файл журнала",
    "Maximum deliberation": "Максимальное обдумывание",
    "More deliberation, slower": "Больше обдумывания, медленнее",
    "New thread in ": "Новый тред в ",
    "Not enough room left in the message for that suggestion": "Недостаточно места в сообщении для этой подсказки",
    "Not enough room left in the message to quote that": "Недостаточно места в сообщении, чтобы процитировать это",
    "Not supported!": "Не поддерживается!",
    "Nothing is running or queued": "Ничего не выполняется и нет очереди",
    "Nothing jotted yet": "Пока нет записей",
    "Open sign-in again": "Снова открыть вход",
    "Open the stash": "Открыть отложенные",
    "Pasting files needs the desktop app": "Для вставки файлов нужно десктопное приложение",
    "Pause queued work": "Поставить очередь на паузу",
    "Picked up draggable item ": "Подхвачен перетаскиваемый элемент ",
    "Pin thread": "Закрепить тред",
    "Pinned thread": "Закреплённый тред",
    "Powerful all-round coding model": "Мощная универсальная модель для кода",
    "Preview failed — open to relaunch": "Предпросмотр не удался — откройте, чтобы перезапустить",
    "Preview is live": "Предпросмотр работает",
    "Preview is starting…": "Предпросмотр запускается…",
    "Project Agent Skill · creates .agents/skills/<name>/SKILL.md": "Проектный навык агента · создаёт .agents/skills/<name>/SKILL.md",
    "Project is unavailable": "Проект недоступен",
    "Project settings…": "Настройки проекта…",
    "Queue paused after an error.": "Очередь поставлена на паузу после ошибки.",
    "Queue paused.": "Очередь на паузе.",
    "Queue skill": "Поставить навык в очередь",
    "Reasoning effort": "Усилие рассуждений",
    "Resume it, or send a message to continue.": "Продолжите её или отправьте сообщение, чтобы продолжить.",
    "Return to Recent": "Вернуть в «Недавние»",
    "Returned thread to Recent": "Тред возвращён в «Недавние»",
    "Run skill": "Запустить навык",
    "Run the Freebuff skill": "Запустить навык Freebuff",
    "Run this thread in a separate Git worktree so its changes don’t affect your current folder.": "Запустить тред в отдельном Git-worktree, чтобы его изменения не затрагивали вашу текущую папку.",
    "Runs from ": "Запускается из ",
    "Saving is paused until they load": "Сохранение приостановлено до их загрузки",
    "Send and resume queue (Enter)": "Отправить и продолжить очередь (Enter)",
    "Send feedback": "Отправить отзыв",
    "Send message": "Отправить сообщение",
    "Send message and resume queue": "Отправить сообщение и продолжить очередь",
    "Send now": "Отправить сейчас",
    "Sending now": "Отправка",
    "Sending now…": "Отправка…",
    "Settings saved": "Настройки сохранены",
    "Share feedback": "Поделиться отзывом",
    "Shared across all available free models.": "Доступно во всех доступных бесплатных моделях.",
    "Shared across all premium models.": "Доступно во всех премиум-моделях.",
    "Shell Session": "Сессия оболочки",
    "Shell closed": "Оболочка закрыта",
    "Showing Freebuff data needs the desktop app.": "Для просмотра данных Freebuff нужно десктопное приложение.",
    "Sign in": "Войти",
    "Sign in to Freebuff": "Войти в Freebuff",
    "Signed in": "Вы вошли",
    "Skill instructions": "Инструкции навыка",
    "Specific to this model.": "Особенность этой модели.",
    "Starting branch": "Стартовая ветка",
    "Stash this message": "Отложить это сообщение",
    "Stop the running turn": "Остановить текущий ход",
    "Stopping the running turn": "Остановка текущего хода",
    "Tab close scheduled": "Закрытие вкладки запланировано",
    "Tell us what went wrong or what you’d like to see.": "Расскажите, что пошло не так или что вы хотели бы видеть.",
    "That turn failed, so the rest of the queue is paused.": "Этот ход завершился ошибкой, поэтому остальная очередь поставлена на паузу.",
    "The queue is paused.": "Очередь на паузе.",
    "This copy is running from a disk image or temporary location, so it cannot replace itself. Download the installer, move Freebuff to Applications, and open it there.": "Эта копия запущена из образа диска или временного расположения, поэтому она не может заменить себя. Скачайте установщик, переместите Freebuff в «Программы» и откройте его там.",
    "This folder isn’t a git repository, so isolated workspaces aren’t available. Threads run directly in the folder.": "Эта папка не является git-репозиторием, поэтому изолированные рабочие области недоступны. Треды выполняются прямо в папке.",
    "This permanently deletes the thread and its saved worktree state.": "Это безвозвратно удалит тред и его сохранённое состояние worktree.",
    "This tab is stopped.": "Эта вкладка остановлена.",
    "This thread runs directly in the shared project folder.": "Этот тред выполняется прямо в общей папке проекта.",
    "This thread runs in a separate Git worktree. Its changes won’t affect your current folder until you apply them.": "Этот тред выполняется в отдельном Git-worktree. Его изменения не затронут вашу текущую папку, пока вы их не примените.",
    "Thread shell": "Оболочка треда",
    "Token usage": "Использование токенов",
    "Type a message — / for skills, @ for files": "Введите сообщение — / для навыков, @ для файлов",
    "Type a message — added to the queue": "Введите сообщение — добавлено в очередь",
    "Type a message — sending resumes the queue": "Введите сообщение — отправка продолжит очередь",
    "Unpin thread": "Открепить тред",
    "Unpinned thread": "Тред откреплён",
    "Update interrupted": "Обновление прервано",
    "Usage incomplete": "Данные об использовании неполные",
    "Use skill now": "Использовать навык сейчас",
    "Waiting for sign-in… (retry)": "Ожидание входа… (повторить)",
    "Weekly limit": "Недельный лимит",
    "What happened, and what did you expect?": "Что произошло и чего вы ожидали?",
    "You have the latest available version. Freebuff will keep checking in the background.": "У вас последняя доступная версия. Freebuff продолжит проверять обновления в фоне.",
    "Your current version is untouched. Try the update again, or download the installer.": "Ваша текущая версия не тронута. Попробуйте обновление ещё раз или скачайте установщик.",
    "Your customized version is deleted and Freebuff’s built-in comes back.": "Ваша изменённая версия будет удалена, и вернётся встроенная Freebuff.",
    "⧉ Copy invite link": "⧉ Копировать ссылку-приглашение",
    "Save copy": "Сохранить копию",
    "Create skill": "Создать навык",
    "Saving…": "Сохранение…",
    "Added": "Добавлено",
    "Edit skills": "Изменить навыки",
    "Done editing skills": "Закончить редактирование навыков",
    # --- Mission panel & effort scale (re-added after app update wiped them) ---
    "Write your own": "Написать свой",
    "What finishing looks like, and what happens to the finished work.": "Что считается готовым и что происходит с готовой работой.",
    "Mission prompt": "Текст миссии",
    "Working toward this mission automatically once the queue finishes. Anything you queue takes over.": "Работаю над этой миссией автоматически после завершения очереди. Всё, что вы добавите в очередь, перебивает её.",
    "Set a mission to keep working toward automatically once the queue finishes": "Задайте миссию — буду работать к ней автоматически после завершения очереди",
    "Edit mission": "Изменить миссию",
    "Deciding what is next…": "Решаю, что делать дальше…",
    "Investigate and report back, changing nothing": "Исследовать и доложить, ничего не меняя",
    "Do the work and commit locally, but never push": "Сделать работу и закоммитить локально, ничего не пушить",
    "Take it all the way to a merged pull request": "Довести всё до влитого pull request",
    "Could not save the mission": "Не удалось сохранить миссию",
    "Could not change mission effort": "Не удалось изменить усилие миссии",
    "Showing the first 512 KB read-only": "Показываются первые 512 КБ только для чтения",
    "Minimal — only a major concrete gain": "Минимальный — только крупный конкретный результат",
    "Lean — buy clear improvements": "Сдержанный — добиваться явных улучшений",
    "Balanced — refine while gains are clear": "Сбалансированный — шлифовать, пока выгода очевидна",
    "Thorough — pursue smaller credible gains": "Основательный — добиваться и мелких правдоподобных улучшений",
    "Exhaustive — stop when gains are marginal": "Исчерпывающий — остановиться, когда прирост маргинален",
    # preset prompts — apostrophes escaped exactly as in the bundle (\')
    "Investigate the user\'s request and report what you find. Do not edit files. Stop and hand back once the question is answered, or as soon as the next move is a decision only the user can make.": "Изучите запрос пользователя и доложите, что нашли. Не изменяйте файлы. Остановитесь и верните управление, как только ответите на вопрос или как только следующий шаг станет решением, которое может принять только пользователь.",
    "Complete the user\'s request fully. When the work is correct, lean, and verified, commit it locally and stop. Never push, open a pull request, or merge — leave the branch for the user to look at.": "Выполните запрос пользователя полностью. Когда работа корректна, лаконична и проверена, закоммитьте её локально и остановитесь. Не пушите, не открывайте pull request и не мержите — оставьте ветку пользователю для просмотра.",
    "Complete the user\'s request fully. When the work is correct, lean, and verified, commit it, open a pull request, drive its checks to green, and merge it.": "Выполните запрос пользователя полностью. Когда работа корректна, лаконична и проверена, закоммитьте её, откройте pull request, доведите его проверки до зелёных и смержите его.",

    "Approved summaries of recent work will appear here.": "Здесь появятся одобренные сводки недавней работы.",
    "Approved work summaries": "Одобренные сводки работы",
    "Automatic": "Автоматически",
    "Check your connection and try again.": "Проверьте подключение и попробуйте снова.",
    "Could not save this file": "Не удалось сохранить файл",
    "Every 3 days": "Каждые 3 дня",
    "Every 5 days": "Каждые 5 дней",
    "Home preferences": "Настройки главного экрана",
    "Install updates": "Устанавливать обновления",
    "Loading updates": "Загрузка обновлений",
    "No summaries published yet": "Сводки ещё не публиковались",
    "Nothing queued.": "В очереди ничего нет.",
    "Once per day": "Раз в день",
    "Open tabs": "Открытые вкладки",
    "Recent work": "Недавняя работа",
    "Released and upcoming work from the past 24 hours.": "Опубликованная и предстоящая работа за последние 24 часа.",
    "Reload from disk": "Перезагрузить с диска",
    "Show recent work": "Показать недавнюю работу",
    "Updates couldn’t load": "Не удалось загрузить обновления",
    "Automatic archive setting was saved, but threads could not be checked:": "Настройка автоматического архивирования сохранена, но проверить треды не удалось:",
    "Running...": "Выполняется…",
    "Command failed.": "Команда завершилась ошибкой.",
    "Command completed with no output.": "Команда завершилась без вывода.",
    "Could not open your workspace": "Не удалось открыть рабочую папку",
    "This file changed on disk. Reload it before you save again.": "Файл изменился на диске. Перезагрузите его, прежде чем сохранять снова.",
    "Freebuff changelog": "Журнал изменений Freebuff",
    # --- New features (post-update): agent mode, question flow, saved missions, referral ---
    "Agent mode": "Режим агента",
    "Plan mode: the agent explores and designs a plan instead of editing files, then asks for approval to build. Takes effect from the next message.": "Режим «План»: агент изучает проект и составляет план вместо правки файлов, затем запрашивает одобрение на сборку. Действует со следующего сообщения.",
    "Build mode: the agent edits files directly. Switch to Plan to design first and approve before building.": "Режим «Сборка»: агент сразу правит файлы. Переключитесь на «План», чтобы сначала спроектировать и одобрить перед сборкой.",
    "The plan is ready for your review": "План готов к проверке",
    "Freebuff has a question": "Freebuff задаёт вопрос",
    "Question ": "Вопрос ",
    " of ": " из ",
    "Previous question": "Предыдущий вопрос",
    "Next question": "Следующий вопрос",
    "Sending…": "Отправка…",
    "Send answers": "Отправить ответы",
    "Or type feedback for the next revision…": "Или напишите отзыв для следующей редакции…",
    "Feedback for the next plan revision": "Отзыв для следующей редакции плана",
    "Or type your own answer…": "Или напишите свой ответ…",
    "Waiting for your answer": "Ожидание вашего ответа",
    "Freebuff asked a question and is waiting for your answer": "Freebuff задал вопрос и ждёт вашего ответа",
    "Could not send answers": "Не удалось отправить ответы",
    "Could not skip the questions": "Не удалось пропустить вопросы",
    "Saved missions": "Сохранённые миссии",
    "Forget this mission": "Забыть эту миссию",
    "Keep this mission for other threads and projects": "Сохранить эту миссию для других тредов и проектов",
    "Engage with a post, level up, and get more daily sessions": "Участвуйте в постах, повышайте уровень и получайте больше ежедневных сессий",
}

# Single-word quoted literals verified to occur only in display (UI) contexts.
# Each word's quoted occurrences were checked against the bundle before adding.
RU_WORDS = {
    "Mission": "Миссия",
    "Effort": "Усилие",
    "Explore": "Исследовать",
    "Commit": "Коммит",
    "Merge PR": "Слить PR",
    "Custom": "Свой",
    # reasoning-effort level names (display map N5)
    "Minimal": "Минимальное",
    "Low": "Низкое",
    "Medium": "Среднее",
    "High": "Высокое",
    "Max": "Максимальное",
    "Ultra": "Ультра",
    # agent-mode switch radio (Plan/Build) + question-flow skip button; all quoted
    # occurrences verified to be display-only labels
    "Build": "Сборка",
    "Plan": "План",
    "Skip": "Пропустить",
}

# Exact raw patterns for display-only fixes: the "Home" tab label (plain "Home"
# must NOT be translated — it is a keyboard keycode and part of keydown
# comparisons) and backtick template-literal fragments of new features (question
# flow, saved missions) that the quoted-literal passes cannot reach.
RU_HOME = {
    '"data-tooltip":"Home"': '"data-tooltip":"Главная"',
    '"aria-label":"Home"': '"aria-label":"Главная"',
    'i?"Home":r.title': 'i?"Главная":r.title',
    'i?"Home":r.projectPath': 'i?"Главная":r.projectPath',
    # question-flow aria-labels built with template literals
    "Your own answer to: ${": "Ваш ответ на: ${",
    "Forget ${": "Забыть ${",
    # question-dock title when there are several questions (static, no plural forms)
    "Freebuff has ${t.questions.length} questions": "Freebuff задаёт вопросы: ${t.questions.length}",
    # quote-selection button (only this UI context; markdown parser keeps its own "Quote")
    '"Quote"]': '"Цитировать"]',
}

# orchestrator.js — exact source literals (keys are the full quoted text as it
# appears in the file; \\u2014 is the literal JS unicode escape, \\' the escaped
# apostrophe). Applied with plain string replace.
RU_ORCH = {
    "\"Complete the user\'s request fully. When the work is correct, lean, and verified, commit it, open a pull request, drive its checks to green, and merge it.\"": "\"Выполните запрос пользователя полностью. Когда работа корректна, лаконична и проверена, закоммитьте её, откройте pull request, доведите его проверки до зелёных и смержите его.\"",
    "\"Minimal \\u2014 only a major concrete gain\"": "\"Минимальный \\u2014 только крупный конкретный результат\"",
    "\"Lean \\u2014 buy clear improvements\"": "\"Сдержанный \\u2014 добиваться явных улучшений\"",
    "\"Balanced \\u2014 refine while gains are clear\"": "\"Сбалансированный \\u2014 шлифовать, пока выгода очевидна\"",
    "\"Thorough \\u2014 pursue smaller credible gains\"": "\"Основательный \\u2014 добиваться и мелких правдоподобных улучшений\"",
    "\"Exhaustive \\u2014 stop when gains are marginal\"": "\"Исчерпывающий \\u2014 остановиться, когда прирост маргинален\"",
}
